# Basic Elements
Pattern        ::= 'I' | 'B' | 'P'
Direction      ::= 'f' | 'r'
Quantifier     ::= '*' | '+'
# Quantifier     ::= '*' | '+' | '{' Number '}'
# Number         ::= Digit+
# Digit          ::= '0' | '1' | ... | '9'
Position       ::= '^' | '_'

# Composite Structures
BasicExpr      ::= Pattern Direction? Quantifier?
AltExpr        ::= BasicExpr ('|' BasicExpr)*

# Groups
Group          ::= '(' AltExpr ')' Quantifier? Position?
NonCapGroup    ::= '(?:' AltExpr ')' Quantifier? Position?

# Top-Level Structure
Expression     ::= Group | NonCapGroup | AltExpr
SequenceExpr   ::= Expression ('>' Expression)*
